= TeX-Converter
James Carlson
:numbered:
:toc:
:stem: 



== Purpose

The aim of +tex-converter+ is to transform an Asciidoc
document containing mathematics into a LaTeX document.
Please see the file [red]#manual.ad# 
in this repository for a more details than presented 
here.

Tex-converter supports two closely-related math formats, [blue]#asciimath#
and [blue]#LaTeX#. With them you can render expressions
such as stem:[ a^2 + b^2 = c^2 ] and

[stem]
++++
 e^{2\pi \sqrt{-1}} = 1
++++
within an Asciidoc file.

(The above won't render properly on github right now, but
will render if this README is run through asciidoctor).


=== Asciimath syntax

Asciimath syntax is
as in
----
    stem:[ a^2 + b^2 = c^2 ]
----

and

----
    [stem]
    ++++
      e^{2\pi \sqrt{-1}} = 1
    ++++
----
These are for inline and display math, respectively
The math content is written in LaTeX.
To activitate asciimath
processing, set [blue]#+:stem:+# or [blue]#+:stem: latexmath+#. 

=== LaTeX syntax

The syntax is standard LaTeX:

----
    $ a^2 + b^2 = c^2 $
----

and

----
    \[ 
      e^{2\pi \sqrt{-1}} = 1 
    \]
----


== Usage

The command

[source]
--
$ asciidoctor -r ./tex-converter.rb -b latex sample1.ad -o sample1.tex
--

will transform [blue]#+sample1.ad+# into the tex file  [blue]#+sample1.tex+#.
It can then be run through +pdflatex+. For a shortcut, use the 
included shell script [blue]#run#:

[source]
--
$ ./run sample1
-- 

This script translates `foo.ad` to `foo.tex`, i.e., it expects
its inputs to have extension `.ad`.

For a more complex example with a lot of math, 
see the file `elliptic.ad` in this repo.
The HTML is rendered at  http://epsilon.my.noteshare.io/notebook/195/?note=782[noteshare.io] for purposes of comparison.


== Files

=== Code

* Ruby
** `tex-converter.rb` -- the driver program to transform asciidoc files to tex files
** `node_processor.rb`-- extends classes in the Asciidoctor module which translate
  Asciidoc elements to TeX elements
** `tex_block.rb` -- strips enclosing escaped braces as needed.
* TeX
** `preamble,tex` -- needed by tex-converter.rb to write a standara LaTeX preamble
** `asciidoc_macros.tex` -- needed to carry out the translation of Asciidoc
   blocks to LaTeX environments
** `macros.tex` -- user macros


=== Test

* `manual.ad` -- describes which elments of Asciidoctor are translated into LaTeX
* `sample1.ad` -- math in conventonal LaTeX form, `$ ... $`, etc.
* `sample2.ad` -- like sample1, but the math is as in `stem:[a^ + b^2 = c^2]`, etc.
* `elliptic.ad`

One should use all four files in testing the code.

== Coverage

=== Asciidoc

The following constructs are among the those handled by `tex-converter.rb` at this time.  Please see `manual.ad` for a complete list.


. Sections through level 5

. Numbered and un-numbered lists, including nested lists.

. Hyperlinks, e.g. `http::asciidoctor.org[Asciidoctor]`.
  
. Bold and italic text

. Hard break: line with trailing `+`


. Roles.  Each role wich is translated into TeX require an entry in the  `asciidoc_tex_macros` file.  For example, the role `[red]`
[red]#which you see in use here# has the entry 
`\newcommand{\rolered}[1]{ \textcolor{red}{#1} }`.






=== LaTeX

A construct like the equation environment,
----
    \[ 
	    \begin{equation} 
		... 
	    \end{equation} 
   \]
---- 
needs to be transformed to ----
---- 
	    \begin{equation} 
		... 
	    \end{equation} 
---- 
There is a tricky point here.  Environments
like the equation environment live outside
of the delimiters `\[ ... \]`. But others live inside. Those
that live outside in LaTeX must have their deliimiters
stripped.  The needed transformation
is given by `TeXBlock.process_environments` in
the file `tex_block.rb`. 


The TeXBlock package addresses the points made
above in the case of both conventional LaTeX syntax
 and the `[stem]` block
syntax.


=== Issues


. The following symbols need to be passed through unchanged

** +--+
** +<+ 
** +>+
** +&+ -- important for typesettig matrices
** +...+ -- horizontal rule


. Some apostrophes and quotes are bad -- they get
translated as +&#1234;+ and TeX chokes on them.








