== Click blocks


Click blocks are like `env`-blocks, except that 
when you open a document, only the title,
not the body of the block, is displayed.
Click on the title to reveal the body;
clicking again will return the body
to its hidden sate.  Click blocks
signal their presence by the blue
color of the title.

.Secret
[click.message]
--
The path to wisdom is written on no
secret map.
--

=== Homework 

Click blocks are useful for writing homework 
problems and study aids.

[env.problem]
--
A 70 kg man had climbed onto a one-meter ledge
at a rock-climbing school.  He was not careful,
and so he slipped and fell.  How fast was he 
going when he landed on the ground?
--

[click.hint]
--
Find his potential energy before he slipped.
That is the same as his kinetic energy 
when he landed.
--

[click.solution]
--
The man's potential energy is $V = mgh$,
where $m$ is his mass, $g = 9.8$ is the acceleration
of gravity,ahd $h$ is the height (1 meter).  All
units are standard international.  One
finds that his potential energy is 686 Joules.
His kinetic energy is 
\[
K  = \frac{1}{2} mv^2
\]
One finds that $v = 4.4 m/sec$, or aout 15 km/hr.
--


[env.problem]
--
When the man fell, the apple that he had carefully set
on the ledge also fell.  How fast was
it going when it hit hit the ground?
--



=== Problem sets

Click blocks are useful for constructing problem sets.
Here we give some mathematics problems.


[env.problem] 
--
Find the solutions to $2x +5y = 1$ and $7x - 3y = 30$.
--

[click.hint]
--
Use the first equation to solve for $y$.  Substitute
into the second equation to get a equation in $x$ alone.
--

[click.advice]
--
If you work _slowly_ and _deliberately_, you can get
this problem right on the first try.  Be sure to check your
answer.
--

[click.solution]
--
$x = \frac{153}{41}$  and $y = -\frac{53}{41}$
--

+++<br/>+++

[env.problem]
--
Find the area under the graph of $y  = x^2$ between $x= 1$ and $x = 2$.
--

[click.solution]
--
\[
  \int_1^2 x^2 dx = \left[  \frac{x^3}{3} \right]_1^2 
   = \frac{2^3}{3} - \frac{1^3}{3} = \frac{7}{3}
\]
--





