== Diophantine Equations


The Pythagorean theorem states that
if stem:[a] and stem:[a] are the altitude
and base of a right triangle,
then
stem:[a^2 + b^2 = c^2],
where $c$ is the hypotenuse.
It was known in ancient times
that $a,b,c = 3,4,5$ are the
sides of a right triangle.
This example leads to the
question of whether the
"Pythagorean equation"
has other solutions.
The answer is, _yes indeed_,
as the result below asserts.


[env.theorem%pyth-eq]
--
The equation
[stem]
++++
  a^2 + b^2 = c^2
++++
has infinitely many non-proportional
integer solutions.
--


It is natural to ask about solutions
to analogue of the Pythagorean
equation, but with exponent
higher than two.  Pierre Fermat
considered this problem and arrived
at the following conclusion.

[env.theorem#mu%fermat-eq]
--
The only solution in the integers
of the equation
\[
  a^3 + b^3 = c^3
\]
are the obvious ones in which one
of the variables is zero.
--

These results constitute the
foundation of the subject of Diophantine equations.
