:numbered:
:toc2:
:max-width: 60%

:stem: latexmath



== Introduction



The aim of Asciidoctor's LaTeX converter is

. To render AsciiDoc documents as LaTeX.

. To add to Asciidoctor's facilities for handling mathematical notation when rendered as HTML

As an example of both features, you can write automatically numbered equations, e.g.,

[env.equation]
--
\int_{|z| = 1} \frac{dz}{z} = 2\pi \sqrt{-1}
--

by writing this in Asciidoc

----
[env.equation]
--
\int_{|z| = 1} \frac{dz}{z} = 2\pi \sqrt{-1}
--
----


To render your document as tex, type the commmand
`asciidoctor-latex foo.adoc`.
To render your document as HTML, use the `html`
backend: type the
command `asciidoctor-latex -b html foo.adoc`.


Automatically numbered theorems, definitions, etc., are
written in the same way

----

[env.theorem#th-pythag#integral]
--
For a right triangle, the square on the hypotenuse is equal to the summ
of the squares of the two remaining sides, i.e.,
\[
     c^2 = a^2 + b^2.
\]
-
----

[env.theorem#th-pythag]
--
For a right triangle, the square on the hypotenuse is equal to the summ
of the squares of the two remaining sides, i.e.,
\[
     c^2 = a^2 + b^2.
\]
--

The optional string `#th-pythag` is a label for purposes of cross-referencing:
----
   <<th-pythag>>
----
Using the above code, we may later refer to <<th-pythag>>.
The cross-referencing style applies to env-blocks in general,
e.g., to

[env.equation#eq-pythag]
--
c^2 = a^2 + b^2
--
Cross-references are made like this:
----
  <eq-pythag>>
----
but the rendered
cross-reference is different: we refer to equation <<eq-pythag>>,
formula <<eq-pythag>>, etc.  The ``[env.code]`` block also receives
special treatment. The source text
----
[env.code#iter]
--
def iter(f, a, n)
  n.times do
    a = f.call(a)
    puts a
  end
  return  a
end
--
----
is rendered as

[env.code#iter]
--
def iter(f, a, n)
  n.times do
    a = f.call(a)
    puts a
  end
  return  a
end
--




== First tests



Below are some examples you can run through Asciidoctor to see what you can do with it.
We assume that you've already installed asciidoctor-latex (see README for instructions).
Now try this

```
  $ asciidoctor -b html eq-latex.adoc
```

After running the above command, you should find the file `eq-latex.html`
next to the source file `eq-latex.adoc`. View it in your browser.
You will need to be connected to the internet so that your browser
can load the MathJax fonts used to render mathematical
notation.footnote:[You can also install the fonts on your system.
See http://www.mathjax.org/help/fonts/[mathjax-fonts]. this will give you faster reponse.
Turning off your internet conneection makes it better still:-(]

Lets test the analogous file written in `stem` format:

```
  $ asciidoctor -r asciidoctor-latex -a stem eq-stem.adoc
```

Now convert our first file into LaTeX by running the command

```
  $ asciidoctor -r asciidoctor-latex -a stem=latexmath -b latex eq-latex.adoc
```
or simply with the wrapper script
```
  $ asciidoctor-latex eq-latex.adoc
```

If all was successful, there will be a file `eq-latex.tex` alongside
your source file `eq-latex.adoc`.  You can process it as you
would any LaTeX file.





== Examples

Below is a list of files which demsonstrate various features
of the converter.  In some cases there are two versions, e.g.
`eq-latex.adoc` and `eq-stem.adoc`, each written in the
indicated format.footnote:[A missing entry in the table
may mean that a feature has not yet been implemented,
or that the file demonstrating it has not yet been
written and/or tested.]  In other cases, there
is the same file appears in both the LaTeX
and the STEM columns.  In those cases
the `-a stem` or `-a stem:latexmath` option
is not required unless there is mathematical
content.

One of the best ways
of learning how to use the features of
Asciidotor LaTeX is to use your
natural talent for reverse-engineering:
run the example, the compare the rendered
file and its source.

[options=header, width=80%, align=center]
|===
| LaTeX | STEM | Comments
| `eq-latex.adoc` | `eq-stem.adoc` | Basic equations
| `eqno-latex.adoc` | --  | Numbered equations
| `theorem-latex.adoc` | -- | Numbered theorems
| `env.adoc` | `env.adoc` | Env blocks
| `click.adoc` | `click.adoc`  | Click blocks
| `code.adoc` | code.adoc` | Code blocks
|===



== Comments on the examples

=== eq-latex

Basic equations, both in-line, as with \(a^2 + b^2 = c^2\),
and displayed, as with
\[
  a^n + b^n = c^n
\]


The environment `[env.equation]` is automatically
numbered by default, as in the examples below.


[env.equation]
--
  a^3 + b^3 = c^3
--


[env.equation]
--
  \int_0^1 x^n dx = \frac{1}{n}
--

Here is how the first equation is done:
----
[env.equation]
--
  a^3 + b^3 = c^3
--
----


=== theorem-latex

Numbered theorems, like the those below.


[env.theorem]
--
\[
  a + (b + c) = (a + b) + c
\]
--

[env.theorem]
--
\[
  a(b+c) = ab + ac
\]
--


=== env

The file `env.adoc`, which only requires the converter,
illustrates general usage of the `env`-block.  It gives
an automatically numbered and titled block.  Thus repeated use
of `[env.objection]` gives this.

[env.objection]
--
This is hearsay.
--

[env.objection]
--
That evidence has not been admitted before the court.
--

The first objection was written like this:

----
[env.objection]
--
This is hearsay.
--
----

=== click


Click blocks are like `env`-blocks, except that
when you open a document, only the title,
not the body of the block, is displayed.
Click on the title to reveal the body;
clicking again will return the body
to its hidden sate.  Click blocks
signal their presence by the blue
color of the title.

.Secret message
[click.message]
--
The path to wisdom is written on no
secret map.
--

Click blocks are useful in making up problem sets,
homework assignments, study guides, etc.


=== code

The file `code.adoc` illstrates the versatilty of the `[env]`
and `[click]` blocks which are used here in their `code` role.
We explain how we do the two blocks below and related pieces
of writing.


[env.code#iter]
--
def iter(f, a, n)
  n.times do
    a = f.call(a)
    puts a
  end
  return  a
end
--

.Results
[click.code%numbered]
--
irb> iter $g, 1.0, 6
1.5
1.4166666666666665
1.4142156862745097
1.4142135623746899
1.414213562373095
1.414213562373095
=> 1.414213562373095
--


== Issues

One should be able to tex this document wihout error
and obtain the desired output.  This is very much a work
in progress.  In particaulr, the following have not yet been resolved.

. Dollars signs used to illustrated command cause LaTeX to choke.
  We need to map dollar sign to escaped dollar sig in
  post-processing for tex.  Or is there a better solution?

. The table block in Asciidoc is not implmented -- or rather,
  is partially implemnted.

. The Click block is not implented in teh TeX output.

. The matrix environment in `eq-stem.adoc` does not render correctly.

. Fix title in latex mode
