== Change Log

////
NOTE: Released on RubyGems.org, plan to
release on GitHub in a few days to bring
into sync.

Next release::
. Introduce option as in [env.remark%plain]
to use normal (non-italic) text in the body
of the environment.
. Equations and equation
alignments are now *not* numbered by default.
To number an equation, do this:
`[eq.equation%numbered]`. For equation
alignments, do
`[eq.equationalign%numbered]`.  Better for
better style!
. Moreover, if an equation
or equation alignment environment is labeled
for cross-referencing, e.g.,
`[env.equation#hohoho]`, then it is numbered.
////

1.5.0.15.dev:: (1) Eliminate automatic inclusion of `macros.tex` if it is present.
(2) Introduce the block macro `include_latex_macros::LATEX_FILE`, where LATEX_FILE is
typically a LaTeX style or macro file, or a path thereto.  For the HTML backend, the file is included
in the source text as `\( FILE CONTENTS \)`.  For the tex backend it is included as-is.

1.5.0.14.dev:: Add the inadvertently omitted file `print.css` to the repository.

1.5.0.13.dev:: (1) Make 'latex' the default dialect: no ``-a dialect=blahblah` switch is needed.
(2) Add file data/print.css for better print output.
(3) Add documentnation on how to use data/print.css.
(4)NOTE: solution in previous line is awkward.  One should be able to access
the css file without copying it form data/ (or useing a long file path)

1.5.0.12.dev:: Fix issue #44 in which the file
macros.tex is ignored in the latex dialect
when using the html backend.

1.5.0.11.dev:: Enable the syntax
`Asciidoctor.convert str, { 'dialect' => 'latex' }`
for specifying the dialect in the Ruby API.

1.5.0.10.dev:: NOTE: Version 1.5.0.10 introduces
a new syntax with switches for three 'dialects'
of asciidoc: asciidoc itself, 'manuscript',
and 'latex'.  More on this later.

----

# Invoke asciidoctor-latex for LaTeX output by
#
#   asciidoctor-latex -a dialect=asciidoc foo.adoc
#   asciidoctor-latex -a dialect=manuscript foo.adoc
#   asciidoctor-latex -a dialect=latex foo.adoc
#
# Be sure to use XeLaTex for tex'ing
# For html output, use
#
#   asciidoctor-latex -a dialect=asciidoc foo.adoc -b html
#   asciidoctor-latex -a dialect=manuscript foo.adoc -b html
#   asciidoctor-latex -a dialect=latex foo.adoc -b html
#
# The above are *source file* options for dialects of asciidoc:
#
#   asciidoc
#   asciidoc-manuscript
#   asciidoc-latex
----

1.5.0.8dev:: One can now say
----
$ asciidoctor-latex -a preprocess=no -b html bar.adoc
----
to suppress preprocessing for the mathematician's
much beloved $.  This makes `asciidoctor-latex`
an almost faithful superset of `asciidoctor`.


1.5.0.7dev:: Introduce the construct `env.include_latex`
as in the example below:
----
[env.include_latex]
--
\include abc.tex
\usepackage{foobar}
--
----
The presence of this block has no effect
on the HTML output.  But when the file
is rendered as LaTeX, the indicated
commands are run. Thus one can specify
the style files etc. that one uses
almost exactly as in LaTeX.


1.5.0.4-6dev:: Missing in action!

1.5.0.3dev::
Double exponents in display math are
now handled properly, and the source display math
expression is passed unchanged to the rendered .tex.
(We replace \[ by +\[ in the preprocessor when it occurs
at the beginnng of a line and likewise for the other bracket).


1.5.0.2dev::
Map \( .. \) back to $ ... $ in the postprocessor when converting to LaTeX.
Thus $ .. $ in the source is passed unchanged to the rendered .tex.

1.5.0.1dev::
New environment: [env.box]

1.5.0dev::
Initial release
