== Change Log

////
NOTE: Released on RubyGems.org, plan to
release on GitHub in a few days to bring
into sync.

Next release::
. Introduce option as in [env.remark%plain]
to use normal (non-italic) text in the body
of the environment.
. Equations and equation
alignments are now *not* numbered by default.
To number an equation, do this:
`[eq.equation%numbered]`. For equation
alignments, do
`[eq.equationalign%numbered]`.  Better for
better style!
. Moreover, if an equation
or equation alignment environment is labeled
for cross-referencing, e.g.,
`[env.equation#hohoho]`, then it is numbered.
////

1.5.0.8dev:: One can now say
----
$ asciidoctor-latex -a preprocess=no -b html bar.adoc
----
to suppress preprocessing for the mathematician's
much beloved $.  This makes `asciidoctor-latex`
an almost faithful superset of `asciidoctor`.


1.5.0.7dev:: Introduce the construct `env.include_latex`
as in the example below:
----
[env.include_latex]
--
\include abc.tex
\usepackage{foobar}
--
----
The presence of this block has no effect
on the HTML output.  But when the file
is rendered as LaTeX, the indicated
commands are run. Thus one can specify
the style files etc. that one uses
almost exactly as in LaTeX.


1.5.0.4-6dev:: Missing in action!

1.5.0.3dev::
Double exponents in display math are
now handled properly, and the source display math
expression is passed unchanged to the rendered .tex.
(We replace \[ by +\[ in the preprocessor when it occurs
at the beginnng of a line and likewise for the other bracket).


1.5.0.2dev::
Map \( .. \) back to $ ... $ in the postprocessor when converting to LaTeX.
Thus $ .. $ in the source is passed unchanged to the rendered .tex.

1.5.0.1dev::
New environment: [env.box]

1.5.0dev::
Initial release
