= AsciiDoc-LaTeX Converter for Asciidoctor
James Carlson

:numbered:
:toc2:
:stem:

== Purpose

Asciidoc-LaTeX defines an extended mathematical syntax
for Asciidoc that closely parallels LaTeX.  The
Asciidoctor-LaTeX converter renders documents written
in this extended markup language into both HTML
and LaTeX.footnote:[Many, but not all Asciidoc language
features are covered by this release.]

Please see the file [path]_manual.adoc_ in this repository for additional details
and for technical information.
The directory `try-out` in this repository contains a set of examples which
show what Asciidoctor-LaTeX can do.  Consult the `README` file
in `try-out` for directions on how to render the examples as
HTML or LaTeX. By comparing the source and rendered files,
you will quickly see how to write Asciidoc LaTeX.
Below, we describe the <<Document format,document formats>> used
for mathematics and the <<Commands for rendering>> into HTML or LaTeX.

Asciidoctor-LaTeX is developed by James Carlson, Jakub Jirutka, and Dan Allen.
_In progress: Cross-compilation to Asciidoctor.js by Guillaume Grosettie makes
possible other uses, among which will be inclusion in the Chrome
Live Preview Extension._


== Installation

=== Using Rubygems

There is a development release.  Beta alert!

=== From repository

If you would like to install a development version from the repository, use:

 $ git clone https://github.com/asciidoctor/asciidoctor-latex.git
 $ cd asciidoctor-latex
 $ gem build asciidoctor-latex.gemspec
 $ gem install *.gem


== Document format

Asciidoctor supports two closely-related math formats, [blue]#Asciidoc-LaTeX#
and [blue]#AsciiMath#.  They are available in both in-line and display forms,
as in the examples $a^2 + b^2 = c^2$ and
$$
   e^{2\pi \sqrt{-1}} = 1.
$$
In Asciidoc-LaTeX
the source text for these is `\$ a^2 + b^2 = c^2 \$` and
----
 \[
    e^{2\pi \sqrt{-1}} = 1,
 \]
----
respectively.  One can also write
----
\$\$
   e^{2\pi \sqrt{-1}} = 1.
\$\$
----
You will need to express dollar-denominated currency using
escaped dollar signs: "He paid \$100 for that theorem" is
rendered from "He paid \\$100 for that theorem."
In AsciiMath, one writes `+++stem:[ a^2 + b^2 = c^2 ]+++`,
and
----
  [stem]
  ++++
    e^{2\pi \sqrt{-1}} = 1.
  ++++
----
The syntax of Asciidoc-LaTeX follows that of LaTeX as closely as possible.


== Asciidoc-LaTeX environments

Asciidoc-LaTeX supports an `env` construct that maps to LaTeX environments.
Thus
----
[env.theorem]
--
There exist infinitely many prime numbers.
--
----
renders as an automatically numbered theorem:

[env.theorem]
--
There exist infinitely many prime numbers.
--
Environments can contain in-line and display mathematics, e.g.,
[env.theorem]
--
A two-by-two matrix is invertible if its determinant is
nonzero, i.e., if
\[
  \left|\begin{matrix} a & b \\ c & d \\ \end{matrix}\right| \ne 0
\]
This result extends to $n\times n$ matrices.
--

Likewise, using `[env.definition]`, we obtain
[env.definition]
--
An integer $n$ is *prime* if (a) it is not $\pm 1$
and (b) it has no divisors other
than $\pm 1$ and $\pm n$.
--

For numbered equations, use `[env.equation]` like this

----
[env.equation]
--
a^{p-1} \equiv 1\ \text{mod}\ p
--
----

to obtain the rendered text

[env.equation]
--
a^{p-1} \equiv 1\ \text{mod}\ p
--
In the equation environment you do not need (nor should you have)
the delimiters  `\$ ... \$` and
`\[ ... \]`.
For directions on making cross-references and labeling theorems, equations, etc., see
the `README` file in the `try-out` directory.  For an extensive
example of the use of Asciidoctor LaTeX, see
http://www.noteshare.io/section/the-fundamental-class-of-projective-space[this].
All of these constructs discussed above are translated into native LaTeX when
the converter is used to produuce tex output.



== Click blocks

Click blocks are similar to `[env]` blocks excep that the body of
the block is not displayed until the user clicks on the heading.
The heading of a click block is displayed in blue.  Once a click
block is "opened", it can be closed by clicking again on the heading.

[click.comment]
--
It is sometimes useful to "hide" a comment in a click block
so as not to unduly disturb the flow of the prose. Click
blocks are also useful for problem sets, since one
can make hints, solutions, etc. clickable.
--

The source for the above comment is

----
[click.comment]
--
It is sometimes useful to "hide" a comment ...
--
----

The default for click blocks is not to number them.
See the file `click.adoc` in the `try-out` directory
for more information.

== Commands for rendering

Asciidoc math files can be rendered

* as HTML.  Use `$ Asciidoc-LaTeX -b html foo.adoc` to produce `foo.html`.
With this command the Asciidoc-LaTeX syntax and extensions will be rendered.
* as LaTeX.  Use `$ asciidoctor-latex foo.adoc` to produce `foo.tex`
as described below.


== Switches

Switch `:stem:` processing on by puttinng the text `:stem:`
in your file.  To turn the switch on and set it to `latexmath`, say
instead of `stem:latexmth`.
