= AsciiDoc-LaTeX Converter for Asciidoctor
James Carlson

:numbered:
:toc2:
:stem:

== Purpose

Asciidoc-LaTeX defines an extended mathematical syntax
for Asciidoc that closely parallels LaTeX.  The
Asciidoctor-LaTeX converter renders documents written
in this extended markup language into both HTML
and LaTeX.footnote:[Many, but not all Asciidoc language
features are covered by this release.]

This README is very brief because mathematical
markup in Asciidoc-LaTeX will not render in GitHub.
For a better view of what Asciidoc-LaTeX does, follow the
installation instructions and then run

----
 $ asciidoctor-latex -b html start.adoc
----
on the files `start.adoc`, etc found
in the directory `examples` of this repository.
This command produces the file `start.html`.
It can be viewed with any browser.  You will
need an internet connection , since the browser
 must load he MathJax fonts.

NOTE: Consult the
http://noteshare.io/book/asciidoctor-latex-manual[Asciidoctor-LaTeX manual]
for more information and for a view of both
source and rendered text for
Asciidoc-LaTeX.  For more information on conversion
of Asciidoc-LaTeX documents to LaTeX, see
`manual.adoc` _(needs update)_.


Asciidoctor-LaTeX is developed by James Carlson, Jakub Jirutka, and Dan Allen.
_In progress: Cross-compilation to Asciidoctor.js by Guillaume Grossetie makes
possible other uses, among which will be inclusion in the Chrome
Live Preview Extension._


== Installation

=== Using Rubygems

There is a development release.  Beta alert!

=== From repository

If you would like to install a development version from the repository, use:

 $ git clone https://github.com/asciidoctor/asciidoctor-latex.git
 $ cd asciidoctor-latex
 $ gem build asciidoctor-latex.gemspec
 $ gem install *.gem


== Document format

Asciidoctor supports two closely-related
math formats, [blue]#Asciidoc-LaTeX#
and [blue]#AsciiMath#.
In Asciidoc-LaTeX,
one can write `$ a^2 + b^2 = c^2 $` and
----
 \[
    e^{2\pi \sqrt{-1}} = 1,
 \]
----
for in-line and dipplay mathematial
text, respectively.
You will need to express dollar-denominated
currency using
escaped dollar signs: "He paid \$100 for that
theore.m"  In AsciiMath, one writes
`+++stem:[ a^2 + b^2 = c^2 ]+++`
and
----
  [stem]
  ++++
    e^{2\pi \sqrt{-1}} = 1.
  ++++
----


== Asciidoc-LaTeX environments

Asciidoc-LaTeX supports an `env` construct that maps to LaTeX environments.
Thus
----
[env.theorem]
--
There exist infinitely many prime numbers.
--
----
renders as an automatically numbered theorem.
Environments can contain in-line and display mathematics, e.g.,
----
[env.theorem]
--
A two-by-two matrix is invertible if
its determinant is nonzero, i.e., if
\[
  \left|\begin{matrix}
    a & b \\
    c & d
  \end{matrix}\right| \ne 0
\]
This result extends to $n\times n$ matrices.
--
----

There is complete freedom in parameter `NAME`
of `[env.NAME]`, Thus,one can write
----
[env.definition]
--
An integer $n$ is *prime* if (a) it is not
$\pm 1$ and (b) it has no divisors other
than $\pm 1$ and $\pm n$.
--
----
or
----
[env.joke]
--
A mathematician, a philosopher, and
a lawyer met at the local bar
for a drink.  The lawyer said ...
--
----
One can make cross references by labeling
the environment as in
----
[env.joke#mathjoke1]
--
A mathematician, a philosopher, and
a lawyer met at the local bar
for a drink.  The lawyer said ...
--
----
then referencing it later as `<<mathjoke1>>`.

Certain environments receive special treatment.
For numbered equations, use `[env.equation]`
like this

----
[env.equation]
--
a^{p-1} \equiv 1\ \text{mod}\ p
--
----

For sets of equations, use `[env,equationalign]`:
----
[env.equationalign]
--
A & = 4\pi r^2 \\
V & = \frac{4}{3} \pi r^3
--
----




== Click blocks

Click blocks are similar to `[env]` blocks excep that the body of
the block is not displayed until the user clicks on the heading.
The heading of a click block is displayed in blue.  Once a click
block is "opened", it can be closed by clicking again on the heading.

----
[click.comment]
--
It is sometimes useful to "hide" a comment
in a click block so as not to unduly
disturb the flow of the prose. Click
blocks are also useful for problem sets,
since one can make hints, solutions, etc.
clickable.
----


The default for click blocks is not to number them.
See the file `click.adoc` in the `exampless` directory
for more information.

== Commands for rendering

Asciidoc math files can be rendered

* as HTML.  Use `$ asciidoctor-latex -b html foo.adoc` to produce `foo.html`.
With this command the Asciidoc-LaTeX syntax and extensions will be rendered.
* as LaTeX.  Use `$ asciidoctor-latex foo.adoc`
to produce `foo.tex`.


== Switches

Switch `:stem:` processing on by puttinng the text `:stem:`
in your file.  To turn the switch on and set it to `latexmath`, say
instead of `stem:latexmth`.
