= AsciiDoc to LaTeX Converter for Asciidoctor
James Carlson
:numbered:
:toc2:
:stem:

== Purpose

The aim of the LaTeX converter is to transform an AsciiDoc document containing
mathematical notation into a LaTeX document.
The converter also adds to Asciidoctor's facilities for handling mathematical
notation when rendered as HTML.  Among these is the automatic numbering of theorems.
Please see the file [path]_manual.adoc_ in this repository for additional details
and for technical information.

For examples and a quick start guide, see <<Getting started>>.
Below, we describe the <<Document format,document formats>> used
for mathematics and the <<Command for rendering,commands>> for rendering a document into HTML or LaTeX.


== Installation

=== Using Rubygems

_asciidoctor-latex has not been released yet_

=== From repository

If you'd like to install a development version from the repository, then use:

 $ git clone https://github.com/asciidoctor/asciidoctor-latex.git
 $ cd asciidoctor-latex
 $ gem build asciidoctor-latex.gemspec
 $ gem install *.gem


== Getting started

The directory `try-out` contains a set of examples which
show what Asciidoctor LateX can do.  Consult the `README` file
for directions on how to render an examples as
HTML or LaTeX. By comparing the source and rendered files,
you will quickly see how to write Asciidoc LaTeX.



== Document format

Asciidoctor supports two closely-related math formats, [blue]#AsciiMath# and [blue]#LaTeX#.
For in-line mathematics, the first looks like `+++stem:[ a^2 + b^2 = c^2 ]+++`, while the
second looks like `$ a^2 + b^2 = c^2 $`.  Both render as stem:[ a^2 + b^2 = c^2 ].
For displayed text, one can use
----
  [stem]
  ++++
    e^{2\pi \sqrt{-1}} = 1
  ++++
----
or
----
  \[
     e^{2\pi \sqrt{-1}} = 1
  \]
----
Both render as
  \[
     e^{2\pi \sqrt{-1}} = 1
  \]
_Please note that the formulae above will not render properly
if you are reading it on GitHub.  It will, however, render properly if you run
this file through Asciidoctor_.

== Commands for rendering

Asciidoc math files can be rendered

. as HTML (the default)
. with the LaTeX converter additions such as automatic theorem numbering
. as LaTeX
+
*Note.* Forthcoming releases will make it possible to render
+
. as PDF
. as EPUB3 (Electronic book)


=== HTML output

To render a file into HTML, the Asciidoctor default,
use the usual `asciidoctor` command with this option:
```
  $ asciidoctor -a stem foo.adoc
```
or with this
```
  $ asciidoctor -a stem=latexmath foo.adoc
```
depending on the format.


=== LaTeX converter additions

To employ the converter additions such as automatic theorem numbering, use
```
  $ asciidoctor -r asciidoctor-latex -a stem=latexmath -b html foo.adoc
```
or
```
  $ asciidoctor-latex -b html foo.adoc
```


=== LaTeX output

To render a file into LaTeX, use the `-r` (require rubygem) and `-b` (backend) option, e.g.:
```
  $ asciidoctor -r asciidoctor-latex -a stem=latexmath -b latex foo.adoc
```
or simply with the wrapper script:
```
  $ asciidoctor-latex foo.adoc
```


== Switches

Switch `:stem:` processing on by putthng the text `:stem:`
in your file.  To turn the swtich on and set it to `latexmath`, say
instaed `stem:latexmth`.
