= AsciiDoc to LaTeX Converter for Asciidoctor
James Carlson
:numbered:
:toc:
:stem:

== Purpose

The aim of the LaTeX converter is to transform an AsciiDoc document containing mathematics into a LaTeX document.
Please see the file [path]_manual.adoc_ in this repository for a more details than presented here.

The LaTeX converter supports two closely-related math formats, [blue]#AsciiMath# and [blue]#LaTeX#.
With the LaTeX converter, you can render expressions such as stem:[ a^2 + b^2 = c^2 ] and

[stem]
++++
e^{2\pi \sqrt{-1}} = 1
++++

within an AsciiDoc file.

(The above won't render properly on GitHub right now, but will render if this README is run through Asciidoctor).

=== Asciimath syntax

AsciiMath syntax is as in

----
stem:[ a^2 + b^2 = c^2 ]
----

and

----
[stem]
++++
e^{2\pi \sqrt{-1}} = 1
++++
----

These are for inline and display math, respectively
The math content is written in LaTeX.
To activitate AsciiMath processing, set [blue]#+:stem:+# or [blue]#+:stem: latexmath+#.

=== LaTeX syntax

The syntax is standard LaTeX:

----
$ a^2 + b^2 = c^2 $
----

and

----
\[
  e^{2\pi \sqrt{-1}} = 1
\]
----

== Installation

=== Using Rubygems

Open a terminal and type (without the leading `$`):

 $ gem install asciidoctor-latex

If you want to install a pre-release version (e.g. a release candidate), use:

 $ gem install asciidoctor-latex --pre

=== From repository

If you’d like to install a development version from the repository, then use:

 $ git clone https://github.com/asciidoctor/asciidoctor-latex.git
 $ cd asciidoctor-latex
 $ gem build asciidoctor-latex.gemspec
 $ gem install *.gem


== Usage

The command:

 $ asciidoctor -r asciidoctor-latex -b latex samples/sample1.adoc

will create a file [path]_samples/sample1.tex_ from [path]_samples/sample1.adoc_.
Then [path]_samples/sample1.tex_ can be run through the +pdflatex+ command.
For a more complex example with a lot of math, see the file [path]_samples/elliptic.adoc_ in this repo.
The HTML is rendered at  http://epsilon.my.noteshare.io/notebook/195/?note=782[noteshare.io] for purposes of comparison.

If you want to run the converter directly without installing the gem, then run it via Bundler:

 $ bundle exec asciidoctor -r asciidoctor-latex -b latex samples/sample1.adoc


== Files

=== Code

* Ruby
  converter.rb:: the driver program to transform asciidoc files to tex files
  node_processor.rb:: extends classes in the Asciidoctor module which translate AsciiDoc elements to TeX elements
  tex_block.rb:: strips enclosing escaped braces as needed

* TeX
  preamble.tex:: needed by latex_converter.rb to write a standara LaTeX preamble
  asciidoc_macros.tex:: needed to carry out the translation of AsciiDoc blocks to LaTeX environments
  macros.tex:: user macros

=== Test

manual.adoc:: describes which elments of Asciidoctor are translated into LaTeX
sample1.adoc:: math in conventonal LaTeX form, `$ ... $`, etc.
sample2.adoc:: like sample1, but the math is as in `stem:[a^ + b^2 = c^2]`, etc.
elliptic.adoc:: a complete example with lots of math
algebraic_varieties.ad:: a draft, very rough, but more like a real math article.

One should use all four files in testing the code.

== Coverage

=== AsciiDoc

The following constructs are among the those handled by the LaTeX converter at this time.
Please see [path]_manual.adoc_ for a complete list.

. Sections through level 5
. Numbered and un-numbered lists, including nested lists.
. Hyperlinks, e.g. `http://asciidoctor.org[Asciidoctor]`.
. Bold and italic text
. Hard break: line with trailing `+`
. Roles.  Each role wich is translated into TeX require an entry in the `asciidoc_tex_macros` file.
For example, the role `[red]` [red]#which you see in use here# has the entry `\newcommand{\rolered}[1]{ \textcolor{red}{#1} }`.

=== LaTeX

A construct like the equation environment:

----
\[
    \begin{equation}
 	...
    \end{equation}
\]
----

needs to be transformed to ----

----
\begin{equation}
...
\end{equation}
----

////
There is a tricky point here.
Environments like the equation environment live outside of the delimiters `\[ ... \]`.
But others live inside.
Those that live outside in LaTeX must have their delimiters stripped.
The needed transformation is given by `TeXBlock.process_environments` in the file `tex_block.rb`.
////

=== LaTeX Environments

The converter transforms open blocks into LaTeX environments.
Thus the source text:

----
.Comment
[[foobar]]
--
This is merely a test.
--
----

is mapped to

----
\begin{Comment}
\label{foobar}
This is merely a test.
\end{Comment}
----

If an identifier as in `[[foobar]]` is not specified, then a label is generated automatically, as in the example below:

----
.Comment
--
This is merely a test.
--
----

is mapped to

----
\begin{Comment}
\label{comment:13}
This is merely a test.
\end{Comment}
----

In this case the "13" means that this
was the 13th unlabeled comment.

The converter has little knowlege of LaTeX, so
it compiles a file of dumb definitions of environments
corresponding to the open blocks it encounters, e.g.,

----
\newtheorem{Comment}{Comment}
----

These definitions are found in the file `new_environments.tex`.
The definition above has no necessary connection with theorem-proving, but it does provide an easy way to define a serviceable environment: "Comment" is in bold, and it is followed by an automatically generated number.
The body of the block is italicized.
The user will likely want to replace theses environment definitions better suited to the task at hand.

The TeXBlock package addresses the points made above in the case of both conventional LaTeX syntax and the `[stem]` block syntax.

=== Issues

. The following symbols need to be passed through unchanged

** +--+
** +<+
** +>+
** +&+ -- important for typesettig matrices
** +...+ -- horizontal rule

. Some apostrophes and quotes are bad -- they get translated as +&#1234;+ and TeX chokes on them.
