= AsciiDoc to LaTeX Converter for Asciidoctor
James Carlson

:numbered:
:toc2:
:stem:

== Purpose

The aim of the LaTeX converter is to transform an AsciiDoc document containing
mathematical notation into a LaTeX document.
The converter also adds to Asciidoctor's facilities for handling mathematical
notation when rendered as HTML.  Among these are the automatic numbering of theorems
and equations.
Please see the file [path]_manual.adoc_ in this repository for additional details
and for technical information.

For examples and a quick start guide, see <<Getting started>>.
Below, we describe the <<Document format,document formats>> used
for mathematics and the <<Command for rendering,commands>> for rendering a document into HTML or LaTeX.


== Installation

=== Using Rubygems

_asciidoctor-latex has not been released yet_

=== From repository

If you would like to install a development version from the repository, use:

 $ git clone https://github.com/asciidoctor/asciidoctor-latex.git
 $ cd asciidoctor-latex
 $ gem build asciidoctor-latex.gemspec
 $ gem install *.gem


== Getting started

The directory `try-out` contains a set of examples which
show what Asciidoctor LateX can do.  Consult the `README` file
for directions on how to render an examples as
HTML or LaTeX. By comparing the source and rendered files,
you will quickly see how to write Asciidoc LaTeX.



== Document format

Asciidoctor supports two closely-related math formats, [blue]#AsciiMath# and [blue]#LaTeX#.
For in-line mathematics, the first looks like `+++stem:[ a^2 + b^2 = c^2 ]+++`, while the
second looks like `$ a^2 + b^2 = c^2 $`.  Both render as stem:[ a^2 + b^2 = c^2 ].
For displayed text, one can use
----
  [stem]
  ++++
    e^{2\pi \sqrt{-1}} = 1
  ++++
----
or
----
  \[
     e^{2\pi \sqrt{-1}} = 1
  \]
----
Both render as
  \[
     e^{2\pi \sqrt{-1}} = 1
  \]
_Please note that the formulae above will not render properly
if you are reading it on GitHub.  It will, however, render properly if you run
this file through Asciidoctor_.

== Asciidoctor environments

Asciidoctor supports an `env` construct that maps to LaTeX environments.
Thus
----
[env.theorem]
--
There exist infinitely many prime numbers.
--
----
renders as an automatically numbered theorem:

[env.theorem]
--
There exist infinitely many prime numbers.
--

Likewise, using `[env.definition]`, we obtain
[env.definition]
--
An integer $n$ is *prime* if (a) it is not $\pm 1$
and (b) it has no divisors other
than $\pm 1$ and $\pm n$.
--

For numbered equations, use `[env.equation]` like this

----
[env.equation]
--
a^{p-1} \equiv 1\ \text{mod}\ p
--
----

to obtain the rendered text

[env.equation]
--
a^{p-1} \equiv 1\ \text{mod}\ p
--



Except for `[env.equation]`, the TeX constructs `$ ... $` and
`\[ ... \]` can be used in `[env]` blocks.
For directions on making cross-references and labeling theorems, equations, etc., see
the `README` file in the `try-out` directory.  For an extensive
example of the use of Asciidoctor LaTeX, see
http://www.noteshare.io/section/the-fundamental-class-of-projective-space[this].
All of these constructs discussed above are translated into native LaTeX when
the converter is used to produuce tex output.



== Click blocks

Click blocks are similar to `[env]` blocks excep that the body of
the block is not displayed until the user clicks on the heading.
The heading of a click block is displayed in blue.  Once a click
block is "opened", it can be closed by clicking again on the heading.

[click.comment]
--
It is sometimes useful to "hide" a comment in a click block
so as not to unduly disturb the flow of the prose. Click
blocks are also useful for problem sets, since one
can make hints, solutions, etc. clickable.
--

The source for the above comment is

----
[click.comment]
--
It is sometimes useful to "hide" a comment ...
--
----

The default for click blocks is not to number them.
See the file `click.adoc` in the `try-out` directory
for more information.

== Commands for rendering

Asciidoc math files can be rendered

. as HTML (the default)
. with the LaTeX converter additions such as automatic theorem numbering
. as LaTeX
+
*Note.* Forthcoming releases will make it possible to render
+
. as PDF
. as EPUB3 (Electronic book)


=== HTML output

To render a file into HTML, the Asciidoctor default,
use the usual `asciidoctor` command with this option:
```
  $ asciidoctor -a stem foo.adoc
```
or with this
```
  $ asciidoctor -a stem=latexmath foo.adoc
```
depending on the format.


=== LaTeX converter additions

To employ the converter additions such as automatic theorem numbering, use
```
  $ asciidoctor -r asciidoctor-latex -a stem=latexmath -b html foo.adoc
```
or
```
  $ asciidoctor-latex -b html foo.adoc
```


=== LaTeX output

To render a file into LaTeX, use the `-r` (require rubygem) and `-b` (backend) option, e.g.:
```
  $ asciidoctor -r asciidoctor-latex -a stem=latexmath -b latex foo.adoc
```
or simply with the wrapper script:
```
  $ asciidoctor-latex foo.adoc
```


== Switches

Switch `:stem:` processing on by puttinng the text `:stem:`
in your file.  To turn the switch on and set it to `latexmath`, say
instead of `stem:latexmth`.
