= The General Theory of Employment, Interest and Money
John Maynard Keynes
:toc2:

== Chapter 2: The Postulates of the Classical Economics

MOST treatises on the theory of value and
production are primarily concerned with the
distribution of a given volume of employed
resources between different uses and with the
conditions which, assuming the employment of this
quantity of resources, determine their relative
rewards and the relative values of their
products.[1]

The question, also, of the volume of the available
resources, in the sense of the size of the
employable population, the extent of natural
wealth and the accumulated capital equipment, has
often been treated descriptively. But the pure
theory of what determines the actual employment of
the available resources has seldom been examined
in great detail. To say that it has not been
examined at all would, of course, be absurd. For
every discussion concerning fluctuations of
employment, of which there have been many, has
been concerned with it. I mean, not that the topic
has been overlooked, but that the fundamental
theory underlying it has been deemed so simple and
obvious that it has received, at the most, a bare
mention.[2]

=== Section I

The ((classical theory of employment)) — supposedly
simple and obvious — has been based. I think, on
two fundamental postulates, though practically
without discussion, namely:

. The wage is equal to the
((marginal product of labour))
+
That is to say, the wage of an employed person is
equal to the value which would be lost if
employment were to be reduced by one unit (after
deducting any other costs which this reduction of
output would avoid); subject, however, to the
qualification that the equality may be disturbed,
in accordance with certain principles, if
competition and markets are imperfect.

. The utility of the wage when a given volume of
labour is employed is equal to the marginal
disutility of that amount of employment.
+
That is to say, the real wage of an employed
person is that which is just sufficient (in the
estimation of the employed persons themselves) to
induce the volume of labour actually employed to
be forthcoming; subject to the qualification that
the equality for each individual unit of labour
may be disturbed by combination between employable
units analogous to the imperfections of
competition which qualify the first postulate.
Disutility must be here understood to cover every
kind of reason which might lead a man, or a body
of men, to withhold their labour rather than
accept a wage which had to them a utility below a
certain minimum.

This postulate is compatible with what may be
called ((’frictional’ unemployment)). For a realistic
interpretation of it legitimately allows for
various inexactnesses of adjustment which stand in
the way of continuous full employment: for
example, unemployment due to a temporary want of
balance between the relative quantities of
specialised resources as a result of
miscalculation or intermittent demand; or to
time-lags consequent on unforeseen changes; or to
the fact that the change-over from one employment
to another cannot be effected without a certain
delay, so that there will always exist in a
non-static society a proportion of resources
unemployed ‘between jobs’. In addition to
‘frictional’ unemployment, the postulate is also
compatible with ‘voluntary’ unemployment due to
the refusal or inability of a unit of labour, as a
result of legislation or social practices or of
combination for collective bargaining or of slow
response to change or of mere human obstinacy, to
accept a reward corresponding to the value of the
product attributable to its marginal productivity.
But these two categories of ‘frictional’
unemployment and ‘voluntary’ unemployment are
comprehensive. The classical postulates do not
admit of the possibility of the third category,
which I shall define below as ‘involuntary’
unemployment.

Subject to these qualifications, the volume of
employed resources is duly determined, according
to the classical theory, by the two postulates.
The first gives us the demand schedule for
employment, the second gives us the supply
schedule; and the amount of employment is fixed at
the point where the utility of the marginal
product balances the disutility of the marginal
employment.

It would follow from this that there are only four
possible means of increasing employment:

. An improvement in organisation or in foresight
which diminishes ‘frictional’ unemployment;

. a decrease in the marginal disutility of
labour, as expressed by the real wage for which.
additional labour is available, so as to diminish
‘voluntary’ unemployment;

. an increase in the marginal physical
productivity of labour in the wage-goods
industries (to use Professor Pigou’s convenient
term for goods upon the price of which the utility
of the money-wage depends);

. an increase in the price of non-wage-goods
compared with, the price of wage-goods, associated
with a shift in the expenditure of
non-wage-earners from wage-goods to
non-wage-goods.

This, to the best of my understanding, is the
stance of Professor Pigou’s Theory of Unemployment —
the only detailed account of the classical theory
of employment which exists.[3]

=== Section II

Is it true that the above categories are
comprehensive in view of the fact that the
population generally is seldom doing as much work
as it would like to do on the basis of the current
wage? For, admittedly, more labour would, as a
rule, be forthcoming at the existing money-wage if
it were demanded.[4] The classical school
reconcile this phenomenon with their second
postulate by arguing that, while the demand for
labour at the existing money-wage may be satisfied
before everyone willing to work at this wage is
employed, this situation is due to an open or
tacit agreement amongst workers not to work for
less, and that if labour as a whole would agree to
a reduction of money-wages more employment would
be forthcoming. If this is the case, such
unemployment, though apparently involuntary, is
not strictly so, and ought to be included under
the above category of ‘voluntary’ unemployment due
to the effects of collective bargaining, etc.

This calls for two observations, the first of
which relates to the actual attitude of workers
towards real wages and money-wages respectively
and is not theoretically fundamental, but the
second of which is fundamental.

Let us assume, for the moment, that labour is not
prepared to work for a lower money-wage and that a
reduction in the existing level of money-wages
would lead, through strikes or otherwise, to a
withdrawal from the labour market of labour which
is now employed. Does it follow from this that the
existing level of real wages accurately measures
the marginal disutility of labour? Not
necessarily. For, although a reduction in the
existing money-wage would lead to a withdrawal of
labour, it does not follow that a fall in the
value of the existing money-wage in terms of
wage-goods would do so, if it were due to a rise
in the price of the latter. In other words, it may
be the case that within a certain range the demand
of labour is for a minimum money-wage and not for
a minimum real wage. The classical school have
tacitly assumed that this would involve no
significant change in their theory. But this is
not so. For if the supply of labour is not a
function of real wages as its sole variable, their
argument breaks down entirely and leaves the
question of what the actual employment will be
quite indeterminate.[5] They do not seem to have
realised that, unless the supply of labour is a
function of real wages alone, their supply curve
for labour will shift bodily with every movement
of prices. Thus their method is tied up with their
very special assumptions, and cannot be adapted to
deal with the more general case.

Now ordinary experience tells us, beyond doubt,
that a situation where labour stipulates (within
limits) for a money-wage rather than a real wage,
so far from being a mere possibility, is the
normal case. Whilst workers will usually resist a
reduction of money-wages, it is not their practice
to withdraw their labour whenever there is a rise
in the price of wage-goods. It is sometimes said
that it would be illogical for labour to resist a
reduction of money-wages but not to resist a
reduction of real wages. For reasons given below
(section III), this might not be so illogical as
it appears at first; and, as we shall see later,
fortunately so. But, whether logical or illogical,
experience shows that this is how labour in fact
behaves.

Moreover, the contention that the unemployment
which characterises a depression is due to a
refusal by labour to accept a reduction of
money-wages is not clearly supported by the facts.
It is not very plausible to assert that
unemployment in the United States in 1932 was due
either to labour obstinately refusing to accept a
reduction of money-wages or to its obstinately
demanding a real wage beyond what the productivity
of the economic machine was capable of furnishing.
Wide variations are experienced in the volume of
employment without any apparent change either in
the minimum real demands of labour or in its
productivity. Labour is not more truculent in the
depression than in the boom — far from it. Nor is
its physical productivity less. These facts from
experience are a prima facie ground for
questioning the adequacy of the classical
analysis.

It would be interesting to see the results of a
statistical enquiry into the actual relationship
between changes in money-wages and changes in real
wages. In the case of a change peculiar to a
particular industry one would expect the change in
real wages to be in the same direction as the
change in money-wages. But in the case of changes
in the general level of wages, it will be found, I
think, that the change in real wages associated
with a change in money-wages, so far from being
usually in the same direction, is almost always in
the opposite direction. When money-wages are
rising, that is to say, it will be found that real
wages are falling; and when money-wages are
falling, real wages are rising. This is because,
in the short period, falling money-wages and
rising real wages are each, for independent
reasons, likely to accompany decreasing
employment; labour being readier to accept
wage-cuts when employment is falling off, yet real
wages inevitably rising in the same circumstances
on account of the increasing marginal return to a
given capital equipment when output is diminished.

If, indeed, it were true that the existing real
wage is a minimum below which more labour than is
now employed will not be forthcoming in any
circumstances, involuntary unemployment, apart
from frictional unemployment, would be
non-existent. But to suppose that this is
invariably the case would be absurd. For more
labour than is at present employed is usually
available at the existing money-wage, even though
the price of wage-goods is rising and,
consequently, the real wage falling. If this is
true, the wage-goods equivalent of the existing
money-wage is not an accurate indication of the
marginal disutility of labour, and the second
postulate does not hold good.

But there is a more fundamental objection. The
second postulate flows from the idea that the real
wages of labour depend on the wage bargains which
labour makes with the entrepreneurs. It is
admitted, of course, that the bargains are
actually made in terms of money, and even that the
real wages acceptable to labour are not altogether
independent of what the corresponding money-wage
happens to be. Nevertheless it is the money-wage
thus arrived at which is held to determine the
real wage. Thus the classical theory assumes that
it is always open to labour to reduce its real
wage by accepting a reduction in its money-wage.
The postulate that there is a tendency for the
real wage to come to equality with the marginal
disutility of labour clearly presumes that labour
itself is in a position to decide the real wage
for which it works, though not the quantity of
employment forthcoming at this wage.

The traditional theory maintains, in short, that
the wage bargains between the entrepreneurs and
the workers determine the real wage; so that,
assuming free competition amongst employers and no
restrictive combination amongst workers, the
latter can, if they wish, bring their real wages
into conformity with the marginal disutility of
the amount of employment offered by the employers
at that wage. If this is not true, then there is
no longer any reason to expect a tendency towards
equality between the real wage and the marginal
disutility of labour.

The classical conclusions are intended, it must be
remembered, to apply to the whole body of labour
and do not mean merely that a single individual
can get employment by accepting a cut in
money-wages which his fellows refuse. They are
supposed to be equally applicable to a closed
system as to an open system, and are not dependent
on the characteristics of an open system or on the
effects of a reduction of money-wages in a single
country on its foreign trade, which lie, of
course, entirely outside the field of this
discussion. Nor are they based on indirect effects
due to a lower wages-bill in terms of money having
certain reactions on the banking system and the
state of credit, effects which we shall examine in
detail in Chapter 19. They are based on the belief
that in a closed system a reduction in the general
level of money-wages will be accompanied, at any
rate in the short period and subject only to minor
qualifications, by some, though not always a
proportionate, reduction in real wages.

Now the assumption that the general level of real
wages depends on the money-wage bargains between
the employers and the workers is not obviously
true. Indeed it is strange that so little attempt
should have been made to prove or to refute it.
For it is far from being consistent with the
general tenor of the classical theory, which has
taught us to believe that prices are governed by
marginal prime cost in terms of money and that
money-wages largely govern marginal prime cost.
Thus if money-wages change, one would have
expected the classical school to argue that prices
would change in almost the same proportion,
leaving the real wage and the level of
unemployment practically the same as before, any
small gain or loss to labour being at the expense
or profit of other elements of marginal cost which
have been left unaltered.[6] They seem, however,
to have been diverted from this line of thought,
partly by the settled conviction that labour is in
a position to determine its own real wage and
partly, perhaps, by preoccupation with the idea
that prices depend on the quantity of money. And
the belief in the proposition that labour is
always in a position to determine its own real
wage, once adopted, has been maintained by its
being confused with the proposition that labour is
always in a position to determine what real wage
shall correspond to full employment, i.e. the
maximum quantity of employment which is compatible
with a given real wage.

To sum up: there are two objections to the second
postulate of the classical theory. The first
relates to the actual behaviour of labour. A fall
in real wages due to a rise in prices, with
money-wages unaltered, does not, as a rule, cause
the supply of available labour on offer at the
current wage to fall below the amount actually
employed prior to the rise of prices. To suppose
that it does is to suppose that all those who are
now unemployed though willing to work at the
current wage will withdraw the offer of their
labour in the event of even a small rise in the
cost of living. Yet this strange supposition
apparently underlies Professor Pigou’s Theory of
Unemployment,[7] and it is what all members of the
orthodox school are tacitly assuming.

But the other, more fundamental, objection, which
we shall develop in the ensuing chapters, flows
from our disputing the assumption that the general
level of real wages is directly determined by the
character of the wage bargain. In assuming that
the wage bargain determines the real wage the
classical school have slipt in an illicit
assumption. For there may be no method available
to labour as a whole whereby it can bring the
general level of money-wages into conformity with
the marginal disutility of the current volume of
employment. There may exist no expedient by which
labour as a whole can reduce its real wage to a
given figure by making revised money bargains with
the entrepreneurs. This will be our contention. We
shall endeavour to show that primarily it is
certain other forces which determine the general
level of real wages. The attempt to elucidate this
problem will be one of our main themes. We shall
argue that there has been a fundamental
misunderstanding of how in this respect the
economy in which we live actually works.

=== Section III

Though the struggle over money-wages between
individuals and groups is often believed to
determine the general level of real wages, it is,
in fact, concerned with a different object. Since
there is imperfect mobility of labour, and wages
do not tend to an exact equality of net advantage
in different occupations, any individual or group
of individuals, who consent to a reduction of
money-wages relatively to others, will suffer a
relative reduction in real wages, which is a
sufficient justification for them to resist it. On
the other hand it would be impracticable to resist
every reduction of real wages, due to a change in
the purchasing-power of money which affects all
workers alike; and in fact reductions of real
wages arising in this way are not, as a rule,
resisted unless they proceed to an extreme degree.
Moreover, a resistance to reductions in
money-wages applying to particular industries does
not raise the same insuperable bar to an increase
in aggregate employment which would result from a
similar resistance to every reduction in real
wages.

In other words, the struggle about money-wages
primarily affects the distribution of the
aggregate real wage between different
labour-groups, and not its average amount per unit
of employment, which depends, as we shall see, on
a different set of forces. The effect of
combination on the part of a group of workers is
to protect their relative real wage. The general
level of real wages depends on the other forces of
the economic system.

Thus it is fortunate that the workers, though
unconsciously, are instinctively more reasonable
economists than the classical school, inasmuch as
they resist reductions of money-wages, which are
seldom or never of an all-round character, even
though the existing real equivalent of these wages
exceeds the marginal disutility of the existing
employment; whereas they do not resist reductions
of real wages, which are associated with increases
in aggregate employment and leave relative
money-wages unchanged, unless the reduction
proceeds so far as to threaten a reduction of the
real wage below the marginal disutility of the
existing volume of employment. Every trade union
will put up some resistance to a cut in
money-wages, however small. But since no trade
union would dream of striking on every occasion of
a rise in the cost of living, they do not raise
the obstacle to any increase in aggregate
employment which is attributed to them by the
classical school.

=== Section IV

We must now define the third category of
unemployment, namely ‘involuntary’ unemployment in
the strict sense, the possibility of which the
classical theory does not admit.

Clearly we do not mean by ‘involuntary’
unemployment the mere existence of an unexhausted
capacity to work. An eight-hour day does not
constitute unemployment because it is not beyond
human capacity to work ten hours. Nor should we
regard as ‘involuntary’ unemployment the
withdrawal of their labour by a body of workers
because they do not choose to work for less than a
certain real reward. Furthermore, it will be
convenient to exclude ‘frictional’ unemployment
from our definition of ‘involuntary’ unemployment.
My definition is, therefore, as follows: Men are
involuntarily unemployed if, in the event of a
small rise in the price of wage-goods relatively
to the money-wage, both the aggregate supply of
labour willing to work for the current money-wage
and the aggregate demand for it at that wage would
be greater than the existing volume of employment.
An alternative definition, which amounts, however,
to the same thing, will be given in the next
chapter (p. 26 below).

It follows from this definition that the equality
of the real wage to the marginal disutility of
employment presupposed by the second postulate,
realistically interpreted, corresponds to the
absence of ‘involuntary’ unemployment. This state
of affairs we shall describe as ‘full’ employment,
both ‘frictional’ and ‘voluntary’ unemployment
being consistent with ‘full” employment thus
defined. This fits in, we shall find, with other
characteristics of the classical theory, which is
best regarded as a theory of distribution in
conditions of full employment. So long as the
classical postulates hold good, unemployment,
which is in the above sense involuntary, cannot
occur. Apparent unemployment must, therefore, be
the result either of temporary loss of work of the
‘between jobs’ type or of intermittent demand for
highly specialised resources or of the effect of a
trade union ‘closed shop’ on the employment of
free labour. Thus writers in the classical
tradition, overlooking the special assumption
underlying their theory, have been driven
inevitably to the conclusion, perfectly logical on
their assumption, that apparent unemployment
(apart from the admitted exceptions) must be due
at bottom to a refusal by the unemployed factors
to accept a reward which corresponds to their
marginal productivity. A classical economist may
sympathise with labour in refusing to accept a cut
in its money-wage, and he will admit that it may
not be wise to make it to meet conditions which
are temporary; but scientific integrity forces him
to declare that this refusal is, nevertheless, at
the bottom of the trouble.

Obviously, however, if the classical theory is
only applicable to the case of full employment, it
is fallacious to apply it to the problems of
involuntary unemployment — if there be such a
thing (and who will deny it?). The classical
theorists resemble Euclidean geometers in a
non-Euclidean world who, discovering that in
experience straight lines apparently parallel
often meet, rebuke the lines for not keeping
straight as the only remedy for the unfortunate
collisions which are occurring. Yet, in truth,
there is no remedy except to throw over the axiom
of parallels and to work out a non-Euclidean
geometry. Something similar is required today in
economics. We need to throw over the second
postulate of the classical doctrine and to work
out the behaviour of a system in which involuntary
unemployment in the strict sense is possible.

=== Section V

In emphasising our point of departure from the
classical system, we must not overlook an
important point of agreement. For we shall
maintain the first postulate as heretofore,
subject only to the same qualifications as in the
classical theory; and we must pause, for a moment,
to consider what this involves.

It means that, with a given organisation,
equipment and technique, real wages and the volume
of output (and hence of employment) are uniquely
correlated, so that, in general, an increase in
employment can only occur to the accompaniment of
a decline in the rate of real wages. Thus I am not
disputing this vital fact which the classical
economists have (rightly) asserted as
indefeasible. In a given state of organisation,
equipment and technique, the real wage earned by a
unit of labour has a unique (inverse) correlation
with the volume of employment. Thus if employment
increases, then, in the short period, the reward
per unit of labour in terms of wage-goods must, in
general, decline and profits increase.[8] This is
simply the obverse of the familiar proposition
that industry is normally working subject to
decreasing returns in the short period during
which equipment etc. is assumed to be constant; so
that the marginal product in the wage-good
industries (which governs real wages) necessarily
diminishes as employment is increased. So long,
indeed, as this proposition holds, any means of
increasing employment must lead at the same time
to a diminution of the marginal product and hence
of the rate of wages measured in terms of this
product.

But when we have thrown over the second postulate,
a decline in employment, although necessarily
associated with labour’s receiving a wage equal in
value to a larger quantity of wage-goods, is not
necessarily due to labour’s demanding a larger
quantity of wage-goods; and a willingness on the
part of labour to accept lower money-wages is not
necessarily a remedy for unemployment. The theory
of wages in relation to employment, to which we
are here leading up, cannot be fully elucidated,
however, until Chapter 19 and its Appendix have
been reached.

=== Section VI

From the time of Say and Ricardo the classical
economists have taught that supply creates its own
demand; meaning by this in some significant, but
not clearly defined, sense that the whole of the
costs of production must necessarily be spent in
the aggregate, directly or indirectly, on
purchasing the product.

In J. S. Mill’s Principles of Political Economy
the doctrine is expressly set forth:

What constitutes the means of payment for
commodities is simply commodities. Each person’s
means of paying for the productions of other
people consist of those which he himself
possesses. All sellers are inevitably, and by the
meaning of the word, buyers. Could we suddenly
double the productive powers of the country, we
should double the supply of commodities in every
market; but we should, by the same stroke, double
the purchasing power. Everybody would bring a
double demand as well as supply; everybody would
be able to buy twice as much, because every one
would have twice as much to offer in exchange.
[Principles of Political Economy, Book III, Chap.
xiv. § 2.]

As a corollary of the same doctrine, it has been
supposed that any individual act of abstaining
from consumption necessarily leads to, and amounts
to the same thing as, causing the labour and
commodities thus released from supplying
consumption to be invested in the production of
capital wealth. The following passage from
Marshall’s Pure Theory of Domestic Values[9]
illustrates the traditional approach:

The whole of a man’s income is expended in the
purchase of services and of commodities. It is
indeed commonly said that a man spends some
portion of his income and saves another. But it is
a familiar economic axiom that a man purchases
labour and commodities with that portion of his
income which he saves just as much as he does with
that he is said to spend. He is said to spend when
he seeks to obtain present enjoyment from the
services and commodities which he purchases. He is
said to save when he causes the labour and the
commodities which he purchases to be devoted to
the production of wealth from which he expects to
derive the means of enjoyment in the future.

It is true that it would not be easy to quote
comparable passages from Marshall’s later work[10]
or from Edgeworth or Professor Pigou. The doctrine
is never stated today in this crude form.
Nevertheless it still underlies the whole
classical theory, which would collapse without it.
Contemporary economists, who might hesitate to
agree with Mill, do not hesitate to accept
conclusions which require Mill’s doctrine as their
premise. The conviction, which runs, for example,
through almost all Professor Pigou’s work, that
money makes no real difference except frictionally
and that the theory of production and employment
can be worked out (like Mill’s) as being based on
‘real’ exchanges with money introduced
perfunctorily in a later chapter, is the modern
version of the classical tradition. Contemporary
thought is still deeply steeped in the notion that
if people do not spend their money in one way they
will spend it in another.[11] Post-war economists
seldom, indeed, succeed in maintaining this
standpoint consistently; for their thought today
is too much permeated with the contrary tendency
and with facts of experience too obviously
inconsistent with their former view.[12] But they
have not drawn sufficiently far-reaching
consequences; and have not revised their
fundamental theory.

In the first instance, these conclusions may have
been applied to the kind of economy in which we
actually live by false analogy from some kind of
non-exchange Robinson Crusoe economy, in which the
income which individuals consume or retain as a
result of their productive activity is, actually
and exclusively, the output in specie of that
activity. But, apart from this, the conclusion
that the costs of output are always covered in the
aggregate by the sale-proceeds resulting from
demand, has great plausibility, because it is
difficult to distinguish it from another,
similar-looking proposition which is indubitable,
namely that income derived in the aggregate by all
the elements in the community concerned in a
productive activity necessarily has a value
exactly equal to the value of the output.

Similarly it is natural to suppose that the act of
an individual, by which he enriches himself
without apparently taking anything from anyone
else, must also enrich the community as a whole;
so that (as in the passage just quoted from
Marshall) an act of individual saving inevitably
leads to a parallel act of investment. For, once
more, it is indubitable that the sum of the net
increments of the wealth of individuals must be
exactly equal to the aggregate net increment of
the wealth of the community.

Those who think in this way are deceived,
nevertheless, by an optical illusion, which makes
two essentially different activities appear to be
the same. They are fallaciously supposing that
there is a nexus which unites decisions to abstain
from present consumption with decisions to provide
for future consumption; whereas the motives which
determine the latter are not linked in any simple
way with the motives which determine the former.

It is, then, the assumption of equality between
the demand price of output as a whole and its
supply price which is to be regarded as the
classical theory’s ‘axiom of parallels’. Granted
this, all the rest follows — the social advantages
of private and national thrift, the traditional
attitude towards the rate of interest, the
classical theory of unemployment, the quantity
theory of money, the unqualified advantages of
laissez-faire in respect of foreign trade and much
else which we shall have to question.

=== Section VII

At different points in this chapter we have made
the classical theory to depend in succession on
the assumptions:

. that the real wage is equal to the marginal
disutility of the existing employment;

. that there is no such thing as involuntary
unemployment in the strict sense;

. that supply creates its own demand in the
sense that the aggregate demand price is equal to
the aggregate supply price for all levels of
output and employment.

These three assumptions, however, all amount to
the same thing in the sense that they all stand
and fall together, any one of them logically
involving the other two.

=== Author’s Footnotes

1. This is in the Ricardian tradition. For Ricardo
expressly repudiated any interest in the amount of
the national dividend, as distinct from its
distribution. In this he was assessing correctly
the character of his own theory. But his
successors, less clear-sighted, have used the
classical theory in discussions concerning the
causes of wealth. Vide Ricardo’s letter to Malthus
of October 9, 1820: “Political Economy you think
is an enquiry into the nature and causes of wealth —
I think it should be called an enquiry into the
laws which determine the division of the produce
of industry amongst the classes who concur in its
formation. No law can be laid down respecting
quantity, but a tolerably correct one can be laid
down respecting proportions. Every day I am more
satisfied that the former enquiry is vain and
delusive, and the latter only the true objects of
the science.”

2. For example, Prof. Pigou in the Economics of
Welfare (4th ed. p. 127) writes (my italics):
“Throughout this discussion, except when the
contrary is expressly stated, the fact that some
resources are generally unemployed against the
will of the owners is ignored. This does not
affect the substance of the argument, while it
simplifies its exposition.”. Thus, whilst Ricardo
expressly disclaimed any attempt to deal with the
amount of the national dividend as a whole, Prof.
Pigou, in a book which is specifically directed to
the problem of the national dividend, maintains
that the same theory holds when there is some
involuntary unemployment as in the case of full
employment.

3. Prof. Pigou’s Theory of Unemployment is
examined in more detail in the Appendix to Chapter
19 below.

4. Cf. the quotation from Prof. Pigou above, p. 5,
footnote.

5. This point is dealt with in detail in the
Appendix to Chapter 19 below.

6. This argument would, indeed, contain, to my
thinking, a large element of truth, though the
complete results of a change in money-wages are
more complex, as we shall show in Chapter 19
below.

7. Cf. Chapter 19, Appendix.

8. The argument runs as follows: n men are
employed, the nth man adds a bushel a day to the
harvest, and wages have a buying power of a bushel
a day. The n + 1 th man, however, would only add
.9 bushel a day, and employment cannot, therefore,
rise to n + 1 men unless the price of corn rises
relatively to wages until daily wages have a
buying power of .9 bushel. Aggregate wages would
then amount to 9/10 (n + 1) bushels as compared
with n bushels previously. Thus the employment of
an additional man will, if it occurs, necessarily
involve a transfer of income from those previously
in work to the entrepreneurs.

9. p. 34.

10. Mr. J. A. Hobson, after quoting in his
Physiology of Industry (p. 102) the above passage
from Mill, points out that Marshall commented as
follows on this passage as early as his Economics
of Industry, p. 154. “But though men have the
power to purchase, they may not choose to use it.”
“But”, Mr Hobson continues, “he fails to grasp the
critical importance of this fact, and appears to
limit its action to periods of ‘crisis’.” This has
remained fair comment, I think, in the light of
Marshall’s later work.

11. Cf. Alfred and Mary Marshall, Economics of
Industry, p. 17: “It is not good for trade to have
dresses made of material which wears out quickly.
For if people did not spend their means on buying
new dresses they would spend them on giving
employment to labour in some other way.” The
reader will notice that I am again quoting from
the earlier Marshall. The Marshall of the
Principles had become sufficiently doubtful to be
very cautious and evasive. But the old ideas were
never repudiated or rooted out of the basic
assumptions of his thought.

12. It is this distinction of Prof. Robbins that
he, almost alone, continues to maintain a
consistent scheme of thought, his practical
recommendations belonging to the same system as
his theory.

https://www.marxists.org/reference/subject/economics/keynes/general-theory/ch02.htm[Source]
