:numbered:
:latex:

== A Short Math Article

++++
\(
%% Blackboard bold

\def\NN{\mathbb{N}}
\def\QQ{\mathbb{Q}}
\def\RR{\mathbb{R}}
\def\ZZ{\mathbb{Z}}

%% Arrows, sets, etc.
\newcommand{\set}[1]{ \{\,#1\,  \} }
\newcommand{\sett}[2]{ \{\,#1\, \mid\, #2\, \} }
\newcommand{\Set}[1]{ \Big\{\,#1\,  \Big\} }
\newcommand{\Sett}[2]{ \Big\{\,#1\, \Big\vert\; #2\,  \Big\} }
\newcommand{\mapright}[1]{\ \smash{ \mathop{\longrightarrow}\limits^{#1}}\ }
\)
++++

This "article" is a demonstration of how one can write
mathematics in Noteshare.  Use arbitrary LaTeX inside
the traditional dollar sign, bracket delimiters, and a form
of the LaTeX environment.  Equation
numbering and cross-referencing is supported, as is the numbered
theorem environment.footnote:[We are working on a prototype
asciidoctor-to-latex converter.  At the present moment it is
adequate to convert this file into LaTeX.  Stay tuned!]

[quote]
--
Observe the footnote reference in the previous paragraph.
The footnote is *way*at the bottom.  However, you can click on
it it reference it.
--


=== Pythagorean triples

One of the first real pieces of mathematics we
learn is this:

[env.theorem#th-pyth]
--
Let $a$, $b$, and $c$ be the sides of a right triangle,
where $c$ is the hypotenuse.  Then $a^2 + b^2 = c^2$.
--

The Pythagorean theorem suggests an equation,
[env.equation#eq-pyth]
--
   x^2 + y^2 = z^2
--
If we demand that the unknowns be integers,
then this is a _Diophantine equation_. We all
know one solution, to equation <<eq-pyth>>, the
3-4-5 triangle.  However, there are many
more,  in fact, infinitely many.  One
way of generating more solutions is to rescale existing ones.
Thus 6-8-10 is a solution. However,
what is  interesting is that there are infinitely
 many _dissimilar solutions_.  One is 5-12-13.
Quite remarkably, there is a clay tablet (Plympton 322) from
Mesopotamia, dated to about 1800 BC, that
contains a list of 15 such
"Pythagorean triples."   See http://en.wikipedia.org/wiki/Plimpton_322[Wikipedia].

It is unlikely
that the Babylonian mathematicians, despite
their sophistication and skill, knew that
equation <<eq-pyth>>
has infinitely many solutions.  This fact is
equivalent to the statement that the unit circle
centered at the origin has infinitely many points
with rational coordinates.

For more information on Pythagorean triplets, see
http://en.wikipedia.org/wiki/Pythagorean_triple[Wikipedia].

=== Another result from ancient times

[env.theorem#th-primes]
--
There are infinitely many primes.
--

.Proof
--
Suppose that there are only finitely many primes, say
$p_1, p_2, \ldots, p_N$.  Let
--

[env.equation#eq-infprimes]
--
  Q = p_1p_2 \cdots p_N + 1
--

This number is is greater than the greatest prime, $p_N$.
Therefore it is composite, and therefore it is divisible
by $p_i$ for some $i$.  But the remainder of $Q$ upon
division by $p_i$ is 1, a contradiction. *Q.E.D.*


=== The work of Fermat

Let us consider <<th-pyth>> once again.  Pierre Fermat asked whether
this family of Diophantine equations $x^d + y^d = z^d$, where
parameter $d$ is greater than two, have any other than the obvious
solutions, e.g., $x, y, z = 1, 0 ,1$ where one variable is zero.
Fermat conjectured that the answer
was no, and he wrote in the margin of Diophantus' treatise that
he had a marvelous proof of this fact, alas, too long to fit int he
space available.  More than 300 years later, Andrew Wiles, using
techniques developed only in the twentieth century, gave a proof of
the theorem of Fermat.

=== The work of Georg Cantor

Georg Cantor introduced the notion of _set_, e.g.,
[env.equation#eq-set-integers]
--
 \NN = \set{ \text{integers} }
         = \set{ 1, 2, 3, \ldots }
--

Story to be continued  ...

However, let's check that our cross-references work.  We learned
about the Pythagorean formula <<eq-pyth>>,  and the
number of solutions it has in <<th-pyth>>.  We also
learned in  <<th-primes>> that prime numbers
are quite abundant in Nature: there are infinitely many of them.
Our last, incomplete section, featuring the set of integers <<eq-set-integers>>,
is devoted to the work of Georg Cantor.
